baseURL = "https://aewingdev.pages.dev/"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
theme = "hugo-texify3"
title = "aewing.dev"

[author]
name = "Andy Ewing"
email = "aewing05@gmail.com"

[taxonomies]
tags = "tags"
categories = "categories"

[params]
title="aewing.dev"
description = "My personal website"
footnote = ""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true

  [params.sharingbuttons]
  facebook = true
  twitter = true
  email = true
  linkedin = true
  reddit = true
  whatsapp = true
  hackernews = true
  telegram = true
